In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, ExtraTreesClassifier ,AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from xgboost import XGBClassifier

In [2]:
df = pd.read_csv("credit_card_fraud_synthetic.csv")
df.head()

     Time        V1        V2        V3        V4        V5   Amount  Class
0  121958 -2.289061 -1.313758 -0.452562 -0.392802  0.224787  1600.89      0
1  146867  1.432482 -1.095302 -0.129910 -1.362911 -1.017335  4191.85      0
2  131932  1.214722 -0.168797  0.581433  0.699020  0.964415  3271.32      0
3  103694 -0.880864  0.110956 -0.203236 -0.243510  0.362543  1377.51      0
4  119879 -0.881879  0.786970  1.110118  0.015365 -1.135162  4838.72      0

In [3]:
df.shape

(1000, 8)

In [4]:
df.columns

Index(['Time', 'V1', 'V2', 'V3', 'V4', 'V5', 'Amount', 'Class'], dtype='object')

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    1000 non-null   int64
 1   V1      1000 non-null   float64
 2   V2      1000 non-null   float64
 3   V3      1000 non-null   float64
 4   V4      1000 non-null   float64
 5   V5      1000 non-null   float64
 6   Amount  1000 non-null   float64
 7   Class   1000 non-null   int64
dtypes: float64(6), int64(2)
memory usage: 62.6 KB

In [6]:
df.describe()

,Time,V1,V2,V3,V4,V5,Amount,Class
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,86194.539000,0.017610,0.069906,-0.022792,0.022354,-0.013218,2577.052080,0.018000
std,50008.474586,1.038301,1.035560,0.992346,0.978387,0.998908,1444.284318,0.133018
min,235.000000,-3.568205,-2.913672,-3.239438,-2.936162,-3.708797,25.890000,0.000000
25%,42052.250000,-0.646795,-0.594730,-0.693360,-0.624690,-0.711692,1358.502500,0.000000
50%,89361.500000,0.031403,0.089010,-0.008512,-0.000167,0.019587,2636.405000,0.000000
75%,127614.750000,0.742573,0.759734,0.666350,0.664478,0.686529,3849.640000,0.000000
max,172627.000000,3.174442,3.260491,2.750723,3.657702,2.840886,4998.710000,1.000000

In [7]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
Amount    0
Class     0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.dropna(inplace=True)
df.drop_duplicates(inplace=True)
df.head()

     Time        V1        V2        V3        V4        V5   Amount  Class
0  121958 -2.289061 -1.313758 -0.452562 -0.392802  0.224787  1600.89      0
1  146867  1.432482 -1.095302 -0.129910 -1.362911 -1.017335  4191.85      0
2  131932  1.214722 -0.168797  0.581433  0.699020  0.964415  3271.32      0
3  103694 -0.880864  0.110956 -0.203236 -0.243510  0.362543  1377.51      0
4  119879 -0.881879  0.786970  1.110118  0.015365 -1.135162  4838.72      0

In [10]:
X = df.drop("Class",axis=1)
y = df["Class"]
y.unique()

array([0, 1])

In [11]:
col = X.columns

scaler = StandardScaler()
X[col] = scaler.fit_transform(X[col])

X.head()

       Time        V1        V2        V3        V4        V5    Amount
0  0.715506 -2.222694 -1.336820 -0.433302 -0.424539  0.238384 -0.676218
1  1.213851  1.363362 -1.125759 -0.107998 -1.416575 -1.005718  1.118620
2  0.915052  1.153530 -0.230622  0.609189  0.691961  0.979191  0.480941
3  0.350105 -0.865763  0.039660 -0.181927 -0.271873  0.376359 -0.830960
4  0.673912 -0.866742  0.692787  1.142218 -0.007147 -1.123733  1.566727

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [13]:
results = []
models = {
    'Decision Tree_C': DecisionTreeClassifier(random_state=42),
    'Random Forest_C': RandomForestClassifier(random_state=42, n_jobs=-1),
    'Extra Trees_C': ExtraTreesClassifier(random_state=42, n_jobs=-1),
    'Gradient Boosting_C': GradientBoostingClassifier(random_state=42),
    'K-Neighbors_C': KNeighborsClassifier(),
    "XGBoost_C": XGBClassifier(random_state=42),
    "AdaBoost_C": AdaBoostClassifier(random_state=42),
}

In [14]:
for name,model in models.items():
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    acc = accuracy_score(y_test,y_pred)
    results.append({
        "Name":name,
        "accuracy_score":acc,
    })

results_df = pd.DataFrame(results)
results_df

                  Name  accuracy_score
0      Decision Tree_C           0.970
1      Random Forest_C           0.980
2        Extra Trees_C           0.980
3  Gradient Boosting_C           0.970
4        K-Neighbors_C           0.980
5            XGBoost_C           0.980
6           AdaBoost_C           0.975

In [15]:
final_model = RandomForestClassifier(random_state=42, n_jobs=-1)
final_model.fit(X_train,y_train)
y_pred = final_model.predict(X_test)
accuracy_score(y_test,y_pred)

0.98

In [ ]:
from joblib import dump
dump(final_model, "final_model.joblib")
dump(scaler, "scaler.joblib")
dump(X.columns.tolist(), "columns.joblib")

['scaler.joblib']